### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec cant decode byte 0xf6 in position 36: invalid start byte

### ISSUE THREAD

**Issue by Higgss0** [blueaxis/Poricom#29]
![resim_2023-01-11_124019779](https://user-images.githubusercontent.com/122441473/211771565-9576a8d2-feee-4b8d-8e91-7637ba1acfa5.png)

Don't know what is the problem need help

**Comment by bluaxees** [comment]
What build and OS version do you have? Are you able to run this on a previous version?

It seems that the app fails to import `tesserocr` for some reason. The maintainer's comment [here](https://github.com/sirfz/tesserocr/issues/85#issuecomment-360997705) says it might be an issue on your system's environment variables. So can you try changing your system variables and see if it works?

**Comment by quanticism** [comment]
I saw a similar but possibly unrelated issue when I browsed into a folder with a Japanese name on Windows 10 and then restarted the program. In order to let the app open without crashing, I had to edit `NAV_ROOT` in utils/config.toml so that it was set to a directory without japanese characters.

![image](https://user-images.githubusercontent.com/87370116/213847739-afc8960e-5e3c-42f2-879e-7f14189684e8.png)

**Comment by quanticism** [comment]
@blueaxis I can reproduce the OP's error by making sure the Poricom files are in a path where there's a Japanese character on Windows 10. E.g. `C:\Users\quanticism\Downloads\Poricom-v0.4.0あ`
